### ISSUE TITLE
mac squeezebox

### ISSUE THREAD

**Issue by jowoo** [philippe44/LMS-to-Raop#1]
On mac squeezebox 7.7.5 the plugin installs but then needs updating but refuses to update. All I can gather is that it will download into the library/caches/squeezebox/DownloadedPlugins folder and then gets removed with server.log printing:

Slim::Utils::PluginDownloader::_downloadDone (176) downloaded RaopBridge to /Users/.../Library/Caches/Squeezebox/DownloadedPlugins/RaopBridge.zip

Slim::Utils::PluginDownloader::_downloadDone (194) digest does not match /Users/.../Library/Caches/Squeezebox/DownloadedPlugins/RaopBridge.zip - RaopBridge will not be installed

**Comment by philippe44** [comment]
Yes, I saw that. I have no idea why MacOS is whining about the digest because it matches and all other platforms are happy about it (Linux x86 and ARM, Windows). So best it to download the zip file form sourceforge and unzip it directly in the LMS plugin folder (/Users/<you>/Library/Caches/Squeezebox/InstalledPlugins/Plugins/RaopBridge

**Comment by philippe44** [comment]
It seems that for no reason I could understand, the 0.2.2.1 had a problem with LMS update. I've created a stable version 0.2.2.2 (you need to add my stable repository to access it)

**Comment by jowoo** [comment]
Very strange, that did the trick. Thanks loads great plugin btw
